# Generated by Django 5.2.1 on 2025-05-19 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('rfid_tag', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='rfid_tag',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.employee'),
        ),
    ]
