# Generated by Django 5.2.1 on 2025-05-21 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_employee_remove_attendancerecord_rfid_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='attendance_type',
            field=models.CharField(choices=[('CHECK_IN', 'Check-in (On Time)'), ('LATE_CHECK_IN', 'Check-in (Late)'), ('CHECK_OUT', 'Check-out'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee'),
        ),
    ]
